name: Release workflow

on:
  push:
    branches: [ "release" ]
  workflow_dispatch:

jobs:
    
  Create-Octopus-Release:
  
      name: Create Octopus Release 🐙
      runs-on: ubuntu-latest
      
      env:
        OCTOPUS_URL: ${{ secrets.OCTOPUS_SERVER_URL }}
        OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_API_KEY }}
        OCTOPUS_SPACE: ${{ secrets.OCTOPUS_SPACE_NAME }}
        
      steps:
      - uses: OctopusDeploy/create-release-action@v3
        id: "create-release"
        with:
          project: "OctoPetShop - Gitflow 1"
          channel: "2 - Release"
      outputs: 
       release_number: ${{ steps.create-release.outputs.release_number }}
